// Builds the standard room API payload, mirroring the existing updateRoom handler.
// Used by applyWholeHouseMVHR and clearWholeHouseMVHR to avoid field mismatches.
export const buildRoomPayload = (room, overrides = {}) => ({
  name:              room.name,
  internalTemp:      room.internalTemp,
  volume:            room.volume,
  floorArea:         room.floorArea,
  roomLength:        room.roomLength,
  roomWidth:         room.roomWidth,
  roomHeight:        room.roomHeight,
  minAirFlow:        room.ventilation.minAirFlow,
  infiltrationRate:  room.ventilation.infiltrationRate,
  mechanicalSupply:  room.ventilation.mechanicalSupply,
  mechanicalExtract: room.ventilation.mechanicalExtract,
  roomType:             room.roomType             || 'living_room',
  hasManualACHOverride: room.hasManualACHOverride || false,
  manualACH:            room.manualACH            || 0,
  extractFanFlowRate:   room.extractFanFlowRate   || 0,
  hasOpenFire:          room.hasOpenFire          || false,
  designConnectionType:    room.designConnectionType    || 'BOE',
  thermalBridgingAddition: room.thermalBridgingAddition ?? 0.10,
  exposedEnvelopeM2:    room.exposedEnvelopeM2    ?? 0,
  hasSuspendedFloor:    room.hasSuspendedFloor    ?? 0,
  isTopStorey:          room.isTopStorey           ?? 0,
  bgVentCount:          room.bgVentCount           ?? 0,
  bgFanCount:           room.bgFanCount            ?? 0,
  bgFlueSmallCount:     room.bgFlueSmallCount      ?? 0,
  bgFlueLargeCount:     room.bgFlueLargeCount      ?? 0,
  bgOpenFireCount:      room.bgOpenFireCount       ?? 0,
  continuousVentType:   room.continuousVentType    || 'none',
  continuousVentRateM3h:room.continuousVentRateM3h ?? 0,
  mvhrEfficiency:       room.mvhrEfficiency        ?? 0,
  ...overrides,
});

// Builds the safe design params payload from a project object.
// Never spread the whole project — rooms, radiatorSpecs, pipeSections etc.
// will cause a 413 Content Too Large on projects with real data.
export const buildDesignParamsPayload = (proj, overrides = {}) => ({
  externalTemp:      proj.externalTemp,
  annualAvgTemp:     proj.annualAvgTemp,
  airDensity:        proj.airDensity,
  specificHeat:      proj.specificHeat,
  designFlowTemp:    proj.designFlowTemp,
  designReturnTemp:  proj.designReturnTemp,
  mcsPostcodePrefix: proj.mcsPostcodePrefix,
  mcsDegreeDays:     proj.mcsDegreeDays,
  mcsOutdoorLowTemp: proj.mcsOutdoorLowTemp,
  mcsHeatPumpType:       proj.mcsHeatPumpType,
  mcsEmitterType:        proj.mcsEmitterType,
  mcsSystemProvides:     proj.mcsSystemProvides,
  mcsCylinderVolume:     proj.mcsCylinderVolume,
  mcsPasteurizationFreq: proj.mcsPasteurizationFreq,
  mcsUFHType:            proj.mcsUFHType,
  mcsBedrooms:           proj.mcsBedrooms,
  mcsOccupants:          proj.mcsOccupants,
  useSAPVentilation:        proj.useSAPVentilation,
  buildingCategory:         proj.buildingCategory,
  dwellingType:             proj.dwellingType,
  numberOfStoreys:          proj.numberOfStoreys,
  shelterFactor:            proj.shelterFactor,
  numberOfBedrooms:         proj.numberOfBedrooms,
  hasBlowerTest:            proj.hasBlowerTest,
  sapAgeBand:               proj.sapAgeBand,
  airPermeabilityQ50:       proj.airPermeabilityQ50,
  numberOfChimneys:         proj.numberOfChimneys,
  numberOfOpenFlues:        proj.numberOfOpenFlues,
  numberOfIntermittentFans: proj.numberOfIntermittentFans,
  numberOfPassiveVents:     proj.numberOfPassiveVents,
  ventilationSystemType:    proj.ventilationSystemType,
  mvhrEfficiency:           proj.mvhrEfficiency,
  mvhrWholeHouseRate:       proj.mvhrWholeHouseRate ?? 0,
  ventilationMethod:      proj.ventilationMethod,
  airPermeabilityMethod:  proj.airPermeabilityMethod,
  q50:                    proj.q50,
  sapStructural:          proj.sapStructural,
  sapFloor:               proj.sapFloor,
  sapWindowDraughtPct:    proj.sapWindowDraughtPct,
  sapDraughtLobby:        proj.sapDraughtLobby,
  buildingStoreys:        proj.buildingStoreys,
  buildingShielding:      proj.buildingShielding,
  referenceTemp:          proj.referenceTemp,
  mcsHeatPumpSoundPower:  proj.mcsHeatPumpSoundPower,
  mcsSoundAssessments:    proj.mcsSoundAssessments    || [],
  mcsSoundSnapshot:       proj.mcsSoundSnapshot       || null,
  mcsCalculationSnapshot: proj.mcsCalculationSnapshot || null,
  pipeSections:           null,
  circuits:               proj.circuits               || null,
  heatPumpManufacturer:   proj.heatPumpManufacturer,
  heatPumpModel:          proj.heatPumpModel,
  heatPumpRatedOutput:    proj.heatPumpRatedOutput,
  heatPumpMinModulation:  proj.heatPumpMinModulation  ?? 0,
  heatPumpFlowTemp:       proj.heatPumpFlowTemp,
  heatPumpReturnTemp:     proj.heatPumpReturnTemp,
  epcSpaceHeatingDemand:  proj.epcSpaceHeatingDemand,
  epcHotWaterDemand:      proj.epcHotWaterDemand,
  epcTotalFloorArea:      proj.epcTotalFloorArea,
  heatPumpInternalVolume: proj.heatPumpInternalVolume ?? 0,
  bufferVesselVolume:     proj.bufferVesselVolume     ?? 0,
  en14511TestPoints:      proj.en14511TestPoints      || [],
  defrostPct:             proj.defrostPct             ?? 5,
  balancePoint:           proj.balancePoint           ?? 12.5,
  scopEmitterType:        proj.scopEmitterType        || 'radiator',
  ...overrides,
});
